config/routes.rb
Rails.application.routes.draw do
  # LOG IN & SIGN UP ROUTES
  devise_for :recruiters
  devise_for :candidates, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # HOME PAGE ROUTE
  root to: 'pages#home'

  # JOB OFFERS & FOLDERS & SEARCH ROUTES
  get '/search', to: 'pages#search', as: 'search'
  resources :job_offer_folders, only: [:create, :update, :destroy]
  resources :job_offers, only: [:index, :create, :edit, :update, :show, :destroy] do


    # JOB APPLICATIONS ROUTES
    resources :job_applications, only: [:index, :show, :edit, :update, :new] do

      get 'toto'
      get 'toto', on: :member
      get 'toto', on: :collection

      post 'submit', on: :member

      collection do #??????
        delete :batch_deletion
      end

      member do
        get 'submit'
      end

    end
  end

  resources :job_applications, only: [] do
    get 'conversation', on: :member
    resources :messages, only: [:create]
  end

  # EXPERIENCES ROUTES
  resources :experiences, only: [:new, :create, :edit, :update, :destroy]

  # EDUCATIONS ROUTES
  resources :educations, only: [:new, :create, :edit, :update, :destroy]

  # LANGUAGES ROUTES
  resources :languages, only: [:new, :create, :edit, :update, :destroy]


  # CANDIDATES ROUTES
  resources :candidates, only: [:show, :edit, :update]

  # DEMO JOB OFFER
  get 'demo', to: 'pages#demo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :job_applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:linkedin]

 def self.find_for_linkedin_oauth(auth)
  current_candidate_params = auth.to_h.slice(:provider, :uid)
  current_candidate_params.merge! auth.info.slice(:email, :first_name, :last_name)
  # current_candidate_params[:linkedin_picture_url] = auth.info.image
  current_candidate_params[:token] = auth.credentials.token
  current_candidate_params[:token_expiry] = Time.at(auth.credentials.expires_at)

  user = self.where(provider: auth.provider, uid: auth.uid).first
  user ||= self.where(email: auth.info.email).first # User did a regular sign up in the past.
  if user
    user.update(current_candidate_params)
  else
    user = self.new(current_candidate_params)
    user.password = Devise.friendly_token[0,20]  # Fake password for validation
    user.save
  end

  return user
end

end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :job_application
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :job_application
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  has_many :languages, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :messages, dependent: :destroy

  belongs_to :candidate
  belongs_to :job_offer

  def recruiter
    job_offer.recruiter
  end
  #permet de faire job_application.recruiter au lieu de job_application.job_offer.recruiter
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :recruiter, required: false
  belongs_to :organization
  belongs_to :job_offer_folder, required: false
  has_many :job_applications
end

app/models/job_offer_folder.rb
class JobOfferFolder < ApplicationRecord
  belongs_to :organization, required: false
  has_many :job_offers

  # self-referential tree structure for Folders
  has_many :job_offer_folders, class_name: "JobOfferFolder", foreign_key: "parent_id"
  belongs_to :parent, class_name: "JobOfferFolder", required: false
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :job_application
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :job_application

  def user
    type = author_role.downcase #????
    self.job_application.send(type)
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :educations
  has_many :recruiters
  has_many :experiences
  has_many :job_offer_folders
  has_many :job_offers
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  belongs_to :organization, required: false
  has_many :job_offers
  has_many :job_applications, through: :job_offers #pour la messagerie
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def self.find_for_linkedin_oauth(auth)
    current_candidate_params = auth.to_h.slice(:provider, :uid)
    current_candidate_params.merge! auth.info.slice(:email)
    # current_candidate_params[:linkedin_picture_url] = auth.info.image
    current_candidate_params[:token] = auth.credentials.token
    current_candidate_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = self.where(provider: auth.provider, uid: auth.uid).first
    user ||= self.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(current_candidate_params)
    else
      user = self.new(current_candidate_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_user = current_candidate || current_recruiter #pour messaging system
  end #pour pouvoir les utiliser dans la navbar car on ne peut pas utiliser dans la view
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="description" content="<%= meta_description %>">
    <%= favicon_link_tag 'higher-favicon.png', type: 'image/png' %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="www.higher.business" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

    <!-- responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <% unless devise_controller? %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/demo.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h4>WHAT CAN YOU EXPECT AS A DIGITAL MARKETING INTERN AT L'ORÉAL</h4>
      <ul>
        <li>You will work in close collaboration with the product manager on the digital strategy of the brand</li>
        <li>You are in charge of the future creation, development and daily follow-up of our digital tools to reinforce the brand image and engage with our customer</li>
        <li>You will help with the organization and realization of tools to create interactivity with our clients, e.g. online contests</li>
        <li>You will participate in creating tools who help us to communicate with the hairdresser and who help the hairdressers to communicate with their clients</li>
        <li>You will work on small marketing projects</li>
      </ul>

      <h4>ARE YOU THE ONE WE ARE LOOKING FOR ?</h4>
      <ul>
        <li>You have a master degree (preferably economics or similar degree)</li>
        <li>You are at least bilingual: Dutch and/or French + English</li>
        <li>You are curious and take initiatives</li>
        <li>You are creative and communicative</li>
        <li>You are problem solving, well organized and have an analytical mindset</li>
      </ul>

      <h4>WHAT'S IN IT FOR YOU ?</h4>
      <ul>
        <li>A remunerated internship of 6 months which will integrate you within an international company and work setting</li>
        <li>A great challenge and competitive advantage on the job market</li>
        <li>The possibility to orientate professionally</li>
      </ul>

      <p>Do you want to kick off your career ?</p>
      <p>Join us !</p>
    </div>
  </div>
</div>
  <% if current_candidate %>
    <div class="text-center">
      <%=  link_to "Apply Now", new_job_offer_job_application_path(@job_offer), class: "btn btn-custom" %>
      <!-- url => higher-wagon.heroku-app.com/job_offers/#{@job_offer.id}/job_applications/new -->
    </div>
  <% else %>
    <div class="text-center">
      <%=  link_to "Apply Now", new_job_offer_job_application_path(@job_offer), class: "btn btn-custom" %>
    </div>
  <% end %>
<br>
<br>
<br>

app/views/pages/search.html.erb
<% content_for :meta_title %>
<% content_for :meta_description %>
<% content_for :meta_image %>

<div class="gray-background">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-xs-offset-0">
        <div class="cv-wrapper"> <!-- div englobbante  -->

          <% if params[:query] %>
            <h2 class="search-header"><%= pluralize(@job_offers.count, "job offer")%> for <strong><%= params[:query] %></strong></h2>
          <% else %>
            <h2 class="search-header"><%= pluralize(@job_offers.count, "job offer") %></h2>
          <% end %>

          <!--job list -->
          <% @job_offers.each do |job_offer| %>
              <%= link_to job_offer_path(job_offer), id: "link-offers" do %>
                <div class="product">
                  <!-- replace img with job_offer.organization.photo_url -->
                    <% if job_offer.recruiter.organization.name == "Oracle" %>
                      <%= image_tag "oracle-logo-organization.png", class: "product-image" %>
                    <% elsif job_offer.recruiter.organization.name == "L'Oréal" %>
                      <%= image_tag "loreal-logo-organization.png", class: "product-image" %>
                    <% elsif job_offer.recruiter.organization.name == "Amazon" %>
                      <%= image_tag "amazon-logo-organization.png", class: "product-image" %>
                    <% end %>
                    <div class='product-body'>
                      <h3 id="orga-name-deco"><%= job_offer.recruiter.organization.name %></h3>
                      <p><%= job_offer.title %></p>
                    </div>
                    <ul class="list-inline product-controls hidden-sm hidden-xs">
                      <li><i class="fa fa-globe"></i> <%= job_offer.location %></li>
                      <li><i class="fa fa-wpforms"></i> <%= job_offer.min_xp.to_i.to_s + "y+" %></li>
                      <li><i class="fa fa-money"></i> <%= job_offer.salary.to_s + "K€" %></li>
                    </ul>
                </div>
              <% end %>
          <% end %>

        </div> <!-- fin div englobbante  -->
      </div>
    </div>
  </div>
</div> <!-- fin couleur de fond black -->

app/views/shared/_flashes.html.erb
<% if 1 == 1 %>
<% else %>
  <% if (params[:controller]) == "job_applications" && params[:action] == "index"  %>
  <% elsif (params[:controller]) == "job_offers" && params[:action] == "index"  %>
  <% else %>
    <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<!-- NAVBAR FOR RECRUITERS -->
<% if recruiter_signed_in? %>
  <%= render "shared/navbar_components/navbar_recruiters" %>

<!-- NAVBAR FOR CANDIDATES (in the application funnel) -->
<% elsif candidate_signed_in? && (params[:controller]) == "job_applications" && params[:action] == "edit" %>
  <%= render "shared/navbar_components/navbar_candidates_funnel" %>

<!-- NAVBAR FOR CANDIDATES (managing their past applications & profile) -->
<% elsif candidate_signed_in? %>
  <%= render "shared/navbar_components/navbar_candidates" %>

<!-- NAVBAR FOR VISITORS (searching) -->
<% elsif (params[:controller]) == "pages" && params[:action] == "search" %>
  <%= render "shared/navbar_components/navbar_visitors_search" %>

<!-- NAVBAR FOR VISITORS (log in & sign up) -->
<% else %>
  <%= render "shared/navbar_components/navbar_visitors" %>

<% end %>

app/views/shared/navbar_components/_navbar_candidates.html.erb
<!-- NAVBAR FOR CANDIDATES (managing their past applications) -->
<div class="navbar-higher"></div> <!-- spacer to compensate the 'fixed navbar offset' -->
<div class="navbar-higher-no-flex navbar-higher-fixed blue-bottom-border">

  <!-- Logo -->
  <div class="margin-top-4px">
    <%= link_to '#', class: "navbar-higher-brand" do %>
      <%= image_tag "name-logo-small.png" %>
    <%end %>
  </div>


  <div class="container"> <!-- notification & links wrapper -->
    <div class="row margin-top-neg-38px">

      <!-- navigation links -->
      <div class="col-xs-4 col-xs-offset-2 margin-top-4px">
        <div class="navbar-higher-links-candidates inline">
          <%= link_to "profile", candidate_path(current_candidate), class: "navbar-higher-link" %>
          <%= link_to "applications", candidate_path(current_candidate), class: "navbar-higher-link" %>
          <%= link_to "jobs", search_path, class: "navbar-higher-link" %>
        </div>
      </div>

     <!-- notification icons -->
      <div class="col-xs-2 col-xs-offset-2">
        <div class="navbar-higher-notifications-candidates">
          <!-- messages -->
          <% if current_user.job_applications.any? %>
            <%= link_to conversation_job_application_path(current_user.job_applications.first), id: "navbar-higher-notification", class: "navbar-higher-link" do %>
              <div class="badge-container inline">
                <i class="fa fa-comments glyphicon-white"></i>
                <div class="badge badge-blue">3</div>
              </div>
            <% end %>
          <% end %>
          <!-- flag -->
          <%= link_to "#", id: "navbar-higher-notification", class: "navbar-higher-link" do %>
            <div class="badge-container inline glyphicon-white">
              <i class="glyphicon glyphicon-flag"></i>
            </div>
          <% end %>
          <!-- user-icon -->
          <%= link_to "#", id: "navbar-higher-notification", class: "navbar-higher-link" do %>
            <div class="badge-container inline">
              <i class="glyphicon glyphicon-user glyphicon-white"></i>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div> <!-- end of links & notfications bootsrap -->


  <!-- dropdown / relative<=>absolute to navbar-higher-funnel -->
  <div>
    <div class="dropdown" id="funnel-logout-triangle-and-name">
      <p class="navbar-higher-link navbar-higher-menu font-20" data-toggle="dropdown" aria-hidden="true">
        <% if current_candidate.first_name %>
          <%= current_candidate.first_name %>
        <% elsif current_candidate.email %>
          <%= current_candidate.email %>
        <% end %>
        <i class="fa fa-caret-down font-25 margin-top-4px"></i>
      </p>

      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to candidate_path(current_candidate) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Account") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_candidate_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div> <!-- end of name + dropdown -->
  </div>



</div> <!-- end of navbar for candidates -->

app/views/shared/navbar_components/_navbar_candidates_funnel.html.erb
<!-- NAVBAR FOR CANDIDATES (in the funnel)-->
<div class="navbar-higher-funnel"></div><!-- spacer to compensate the 'fixed navbar offset' -->
<div class="navbar-higher-funnel navbar-higher-fixed">

  <!-- Logo Recruiter / relative<=>absolute to navbar-higher-funnel -->
  <div class="navbar-higher-brand-recruiter">
    <%= image_tag "LOreal_white_vector.png" %>
  </div>

  <!-- Logo Higher / relative<=>absolute to navbar-higher-funnel -->
  <div class="navbar-higher-brand-funnel">
    <%= image_tag "name-logo-small.png" %>
  </div>

  <!-- dropdown / relative<=>absolute to navbar-higher-funnel -->
    <div class="dropdown" id="funnel-logout-triangle">
      <i class="fa fa-caret-down navbar-higher-menu" data-toggle="dropdown" aria-hidden="true"></i>

      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to candidate_path(current_candidate.id) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Account") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_candidate_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div> <!-- end of dropdown -->

  <!-- FUNNEL STEPS DASHBOARD + IMPORT DATA + VIEW AS EMPLOYER -->
  <div class="container">
    <div class="row min-width-800px">

      <!-- import data button -->
      <div class="col-xs-2 col-xs-offset-2">
        <h6 class="funnel-title-options funnel-title-options-left font-23">import</h6>
        <h6 class="funnel-title-options font-17"><i class="fa fa-linkedin-square" aria-hidden="true"></i> data <i class="fa fa-folder-open" aria-hidden="true"></i></h6>
      </div>

      <!-- flex dev with 3 circles -->
      <div class="col-xs-4">
        <div class="funnel-steps-flexbox" >

          <!-- job -->
          <div class="tabs" data-target="#job-offer">
            <div class="circle">
              <p class="circle-numbers">1</p>
            </div>
            <h6 class="funnel-titles">job</h6>
          </div>
          <!-- resume -->
          <div class="tabs relative" data-target="#resume">
            <div class="circle text-center">
              <p class="circle-numbers">2</p>
            </div>
            <h6 class="funnel-titles">résumé</h6>
            <div class="left-bar-resume"></div>
            <div class="right-bar-resume"></div>
          </div>
          <!-- cover letter -->
          <div class="tabs" data-target="#cover-letter">
            <div class="circle text-center">
              <p class="circle-numbers">3</p>
            </div>
            <h6 class="funnel-titles">details</h6>
          </div>

        </div>
      </div>

      <!-- view as employer button -->
      <a href="" data-toggle="modal" data-target="#ViewAsEmployerModal">
        <div class="col-xs-2" id="button-view-as-employer">
          <h6 class="funnel-title-options funnel-title-options-right text-right font-20"><i class="fa fa-eye" aria-hidden="true"></i> view as</h6>
          <h6 class="funnel-title-options text-right font-21">employer</h6>
        </div>
      </a>
    </div> <!-- end of row -->
  </div> <!-- end of container -->

</div> <!-- end of navbar -->

app/views/shared/navbar_components/_navbar_recruiters.html.erb
<!-- NAVBAR FOR RECRUITERS -->
<div class="navbar-higher"></div> <!-- spacer to compensate the 'fixed navbar offset' -->
<div class="navbar-higher navbar-higher-fixed">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-higher-brand" do %>
    <%= image_tag "name-logo-small.png" %>
  <%end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-higher-search">
      <input type="text" class="navbar-higher-search-input" style="line-height: 30px;" placeholder="Search for candidates & jobs">
      <button type="submit" class="navbar-higher-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- spacer: empty flex-box -->
    <div class="blank-2-percent"></div>

    <!-- navigation links -->
    <div class="navbar-higher-links text-center">
      <%= link_to "jobs", job_offers_path, class: "navbar-higher-link" %>
      <%= link_to "candidates", job_offers_path, class: "navbar-higher-link" %>
      <%= link_to "stats", root_path, class: "navbar-higher-link" %>
    </div>

    <!-- notification icons -->
    <div class="navbar-higher-notifications">
      <% if current_user.job_applications.any? %>
        <%= link_to conversation_job_application_path(current_user.job_applications.first), id: "navbar-higher-notification", class: "navbar-higher-link" do %>
          <div class="badge-container inline">
            <i class="fa fa-comments" aria-hidden="true"></i>
            <div class="badge badge-blue">3</div>
          </div>
        <% end %>
      <% end %>

      <%= link_to "#", id: "navbar-higher-notification", class: "navbar-higher-link" do %>
        <div class="badge-container inline">
          <i class="glyphicon glyphicon-flag"></i>
        </div>
      <% end %>
      <%= link_to "#", id: "navbar-higher-notification", class: "navbar-higher-link" do %>
        <div class="badge-container inline">
          <i class="glyphicon glyphicon-user"></i>
        </div>
      <% end %>
    </div>

    <!-- space:empty flex-box -->
    <div class="blank-5-percent"></div>
    <!-- space:empty flex-box -->
    <div class="blank-5-percent"></div>

    <!-- dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-caret-down font-25 navbar-higher-menu" data-toggle="dropdown" aria-hidden="true"></i>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_candidate_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div> <!-- end of dropdown -->
  </div>
</div> <!-- end of navbar for recruiters -->

app/views/shared/navbar_components/_navbar_visitors.html.erb
<!-- NAVBAR FOR VISITORS -->
<div class="navbar-higher"></div> <!-- spacer to compensate the 'fixed navbar offset' -->
<div class="navbar-higher navbar-higher-fixed blue-bottom-border">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-higher-brand" do %>
    <%= image_tag "name-logo-small.png" %>
  <%end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">

  <div class="navbar-content-visitor">
    <p>The superior way to hire</p>
  </div>


    <!-- Jobs links & about -->
    <div>
      <%= link_to "connect as recruiter", job_offers_path, class: "btn btn-primary", id: "btn-recruiter" %>
      <%= link_to "connect as candidate", new_candidate_session_path, class: "btn btn-primary", id: "btn-candidate" %>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to ("connect as recruiter"), job_offers_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to ("connect as candidate"), new_candidate_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
      </ul>
    </div>
  </div>

</div> <!-- end of navbar -->

app/views/shared/navbar_components/_navbar_visitors_search.html.erb
<!-- NAVBAR FOR VISITORS -->
<div class="navbar-higher"></div> <!-- spacer to compensate the 'fixed navbar offset' -->
<div class="navbar-higher navbar-higher-fixed blue-bottom-border">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-higher-brand" do %>
    <%= image_tag "name-logo-small.png" %>
  <%end %>


  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Search form -->
    <form action="" class="navbar-higher-search">
      <input type="text" class="navbar-higher-search-input" style="line-height: 30px;">
      <button type="submit" class="navbar-higher-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Jobs links & about -->
    <div>
      <%= link_to "connect as recruiter", job_offers_path, class: "btn btn-primary", id: "btn-recruiter" %>
      <%= link_to "connect as candidate", new_candidate_session_path, class: "btn btn-primary", id: "btn-candidate" %>
    </div>

  </div>

<!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to ("connect as recruiter"), job_offers_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to ("connect as candidate"), new_candidate_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
      </ul>
    </div>
  </div>
</div> <!-- end of navbar -->