config/routes.rb
Rails.application.routes.draw do
  # LOG IN & SIGN UP ROUTES
  devise_for :recruiters
  devise_for :candidates, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # HOME PAGE ROUTE
  root to: 'pages#home'

  # JOB OFFERS & FOLDERS & SEARCH ROUTES
  get '/search', to: 'pages#search', as: 'search'
  resources :job_offer_folders, only: [:create, :update, :destroy]
  resources :job_offers, only: [:index, :create, :edit, :update, :show, :destroy] do


    # JOB APPLICATIONS ROUTES
    resources :job_applications, only: [:index, :show, :edit, :update, :new] do

      get 'toto'
      get 'toto', on: :member
      get 'toto', on: :collection

      post 'submit', on: :member

      collection do #??????
        delete :batch_deletion
      end

      member do
        get 'submit'
      end

    end
  end

  resources :job_applications, only: [] do
    get 'conversation', on: :member
    resources :messages, only: [:create]
  end

  # EXPERIENCES ROUTES
  resources :experiences, only: [:new, :create, :edit, :update, :destroy]

  # EDUCATIONS ROUTES
  resources :educations, only: [:new, :create, :edit, :update, :destroy]

  # LANGUAGES ROUTES
  resources :languages, only: [:new, :create, :edit, :update, :destroy]


  # CANDIDATES ROUTES
  resources :candidates, only: [:show, :edit, :update]

  # DEMO JOB OFFER
  get 'demo', to: 'pages#demo'

end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :job_applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:linkedin]

 def self.find_for_linkedin_oauth(auth)
  current_candidate_params = auth.to_h.slice(:provider, :uid)
  current_candidate_params.merge! auth.info.slice(:email, :first_name, :last_name)
  # current_candidate_params[:linkedin_picture_url] = auth.info.image
  current_candidate_params[:token] = auth.credentials.token
  current_candidate_params[:token_expiry] = Time.at(auth.credentials.expires_at)

  user = self.where(provider: auth.provider, uid: auth.uid).first
  user ||= self.where(email: auth.info.email).first # User did a regular sign up in the past.
  if user
    user.update(current_candidate_params)
  else
    user = self.new(current_candidate_params)
    user.password = Devise.friendly_token[0,20]  # Fake password for validation
    user.save
  end

  return user
end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:edit, :update, :show]
  skip_before_action :authenticate_recruiter!
  skip_before_action :verify_authenticity_token

  def edit
    authorize @candidate
  end

  def update
    authorize @candidate

    @candidate.update(candidate_params)
     if @candidate.save
      redirect_to edit_candidate_path
    else
      render :edit
    end
  end

  def show
    authorize @candidate
  end

  private

  def pundit_user
    current_candidate
  end


  def candidate_params
    params.require(:candidate).permit(:email, :first_name, :last_name, :phone_number)
  end

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/edit.html.erb
<div  id="content-padded" >
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
      <% if current_candidate.first_name %>
        <h2 id="title-candidate-padded"><%= @candidate.first_name + " " + @candidate.last_name %> </h2>
        <p><strong> Phone number </strong> : <%= @candidate.phone_number %></p>
        <p><strong> Email </strong> : <%= @candidate.email %></p>
      <% else %>
        <h2 id="title-candidate-padded">All we have on you is :</h2>
        <p><strong> Email </strong> : <%= @candidate.email %></p>
        <p>Give us more !</p>
      <% end %>
        <button type="button" id="button-candidate" class="btn btn-warning" data-toggle="modal" data-target="#EditInfoModal">Edit Info</button>
      </div>
    </div>
  </div>
</div>

<!-- modal Edit info user -->
<div class="modal fade" id="EditInfoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Update your info</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for([ current_candidate ]) do |form| %>
            <%= form.input :first_name %>
            <%= form.input :last_name %>
            <%= form.input :phone_number %>
            <%= form.button :submit %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<div  id="content-padded">
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
          <% if current_candidate.first_name && current_candidate.phone_number.nil? %>
          <h2 id="title-candidate-padded"><%= @candidate.first_name + " " + @candidate.last_name %> </h2>
          <h4 id="title-candidate-padded" class="text-center">What's your number ?<br><br><%= link_to "Give it here !", edit_candidate_path %></h4>
        <% elsif current_candidate.first_name %>
          <h2 id="title-candidate-padded"><%= @candidate.first_name + " " + @candidate.last_name %> </h2>
        <% else  %>
          <h3 id="title-candidate-padded" class="text-center">Who are you ?<br><br><%= link_to "Fill your profile !", edit_candidate_path %></h3>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @candidate.job_applications.any? %>

  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="line">
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="text-center">
        <div class="col-xs-6 col-xs-offset-3">


      <h3 id="padding-title">You candidate for</h3>
          <% @candidate.job_applications.each do |job_application| %>

              <button type="button" id="button-candidate" class="btn-show-application" data-toggle="modal" data-target="#ShowInfoJobApp_<%= job_application.id %>"><i class="glyphicon glyphicon-flash"></i><%= " " + job_application.job_offer.title + " " %><i class="glyphicon glyphicon-flash"></i></button>

            <p><%= link_to "see your job application", job_offer_job_application_path(job_application.job_offer, job_application) %></p>

            <% end %>
        </div>
      </div>
    </div>
  </div>

<% else %>

  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="line">
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="text-center">
        <div class="col-xs-4 col-xs-offset-4">

          <h3 id="padding-title">You haven't applied to a job yet</h3>
          <p>See all the job offers we have for you</p>

        <!-- Need to ajust the path -->
            <%= link_to  "Have a look !", search_path %>

        </div>
      </div>
    </div>
  </div>

<% end %>

<!-- Modal Show infos of applications -->
<% @candidate.job_applications.each do |job_application| %>
  <div class="modal fade" id="ShowInfoJobApp_<%= job_application.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title text-center" id="myModalLabel"><%= job_application.job_offer.title %></h4>
        </div>
        <div class="modal-body text-justify" id="modaloo">
          <%= job_application.job_offer.description %>
          <p> <%= " " %> </p>
          <p>You applied on : <%= job_application.created_at.strftime("%b %d, %Y") %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>