config/routes.rb
Rails.application.routes.draw do
  # LOG IN & SIGN UP ROUTES
  devise_for :recruiters
  devise_for :candidates, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # HOME PAGE ROUTE
  root to: 'pages#home'

  # JOB OFFERS & FOLDERS & SEARCH ROUTES
  get '/search', to: 'pages#search', as: 'search'
  resources :job_offer_folders, only: [:create, :update, :destroy]
  resources :job_offers, only: [:index, :create, :edit, :update, :show, :destroy] do


    # JOB APPLICATIONS ROUTES
    resources :job_applications, only: [:index, :show, :edit, :update, :new] do

      get 'toto'
      get 'toto', on: :member
      get 'toto', on: :collection

      post 'submit', on: :member

      collection do #??????
        delete :batch_deletion
      end

      member do
        get 'submit'
      end

    end
  end

  resources :job_applications, only: [] do
    get 'conversation', on: :member
    resources :messages, only: [:create]
  end

  # EXPERIENCES ROUTES
  resources :experiences, only: [:new, :create, :edit, :update, :destroy]

  # EDUCATIONS ROUTES
  resources :educations, only: [:new, :create, :edit, :update, :destroy]

  # LANGUAGES ROUTES
  resources :languages, only: [:new, :create, :edit, :update, :destroy]


  # CANDIDATES ROUTES
  resources :candidates, only: [:show, :edit, :update]

  # DEMO JOB OFFER
  get 'demo', to: 'pages#demo'

end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :recruiter, required: false
  belongs_to :organization
  belongs_to :job_offer_folder, required: false
  has_many :job_applications
end

app/controllers/job_offers_controller.rb
  class JobOffersController < ApplicationController
  before_action :set_job_offer, only: [:show, :edit, :update]
  skip_before_action :authenticate_candidate!

  skip_before_action :authenticate_recruiter!, only: [:show]

  helper_method :all_children_folders

  def index
    @job_offers = policy_scope(JobOffer) # Pundit authorization
    @job_offers = JobOffer.where(organization: current_recruiter.organization).sort_by { |job_offer| job_offer.title }
    @job_offer_folders = JobOfferFolder.where(organization: current_recruiter.organization).sort_by { |folder| folder.name }
    @job_applications = []
    @job_offers.each do |job_offer|
      @job_applications << job_offer.job_applications
    end
    @job_applications.flatten!
    # DRY recursive tree-structure
    @parent_folders = current_recruiter.organization.job_offer_folders.where(parent: nil).sort_by { |folder| folder.name }
    @all_folders = JobOfferFolder.where(organization: current_recruiter.organization).all.sort_by { |folder| folder.name }
    @orphan_offers = JobOffer.where(organization: current_recruiter.organization, job_offer_folder: nil).sort_by { |offer| offer.title }
    # MODAL DATA
    @job_offer = JobOffer.new # for job_offer creation
    @job_offer_folder = JobOfferFolder.new # for folder (job offers) creation
  end

  def show
    @job_offer = JobOffer.find(params[:id])
    authorize @job_offer
  end

  def create
    @job_offer = JobOffer.new(job_offer_params)
    @job_offer.recruiter = current_recruiter
    @job_offer.organization = current_recruiter.organization
    authorize @job_offer
    if @job_offer.save
      redirect_to job_offers_path
    else
      render :new
    end
  end

  def edit
    @job_offer = JobOffer.find(params[:id])
    authorize @job_offer
  end

  def update
    if job_offer_update_params[:type] == "star"  # add/remove star ajax
      @job_offer = JobOffer.find(job_offer_update_params[:id])
      authorize @job_offer
      @job_offer.star == true ? @job_offer.star = false : @job_offer.star = true
      @job_offer.save
      respond_to do |format|
        format.html { redirect_to job_offers_path }
        format.js { render 'job_offer_star'}
      end
    else
      # todo
      @job_offer = JobOffer.find(job_offer_update_params[:id])
      authorize @job_offer
      @job_offer.update(job_offer_params)
      redirect_to job_offers_path
    end
  end

  def destroy
    @job_offer = JobOffer.find(params[:id])
    authorize @job_offer
    @job_offer.destroy
    redirect_to job_offers_path
  end

  private

  def all_children_folders(parent, children_array = [])
    children = JobOfferFolder.where(parent_id: parent.id)
    children_array << children
    children.each do |child|
      return all_children_folders(child, children_array)
    end
    return children_array.flatten
  end

  def pundit_user
    current_recruiter
  end

  def job_offer_params
    params.require(:job_offer).permit(:description, :title, :job_offer_folder_id)
  end

  def job_offer_update_params
    params.permit(:id, :type)
  end


  def set_job_offer
    @job_offer = JobOffer.find(params[:id])
  end
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/views/job_offers/edit.html.erb
<h1><%= @job_offer.title %></h1>

<div class="dropdown" style="position:relative">

  <!-- loop over parent folders -->



  <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Active <span class="caret"></span></a>
  <!-- level 1 -->
  <ul class="dropdown-menu">
    <% @parent_folders.each do |parent_folder| %>
    <li>
      <a class="trigger right-caret"><%= parent_folder.name %></a>

      <!-- level 2 -->
      <ul class="dropdown-menu sub-menu">
        <% parent_folder.job_offer_folders.each do |folder_lvl2| %>
        <li>
          <a class="trigger right-caret"><%= folder_lvl2.name %></a>

          <!-- level 3 -->
          <ul class="dropdown-menu sub-menu">
          <% folder_lvl2.job_offer_folders.each do |folder_lvl3| %>
            <li>
              <a class="trigger right-caret"><%= folder_lvl3.name %></a>

              <!-- level 4 -->
              <ul class="dropdown-menu sub-menu">
              <% folder_lvl3.job_offer_folders.each do |folder_lvl4| %>
                <li><a href="#">Level 4</a></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <% folder_lvl3.job_offers.each do |offer| %>
                <li><%= link_to offer.title, job_offer_job_applications_path(offer) %></li>
              <% end %>
              </ul>
            </li>
            <% end %>
            <% if folder_lvl2.job_offers.empty? %>
            <% else %>
              <li role="separator" class="divider"></li>
              <% folder_lvl2.job_offers.each do |offer| %>
                <li><%= link_to offer.title, job_offer_job_applications_path(offer) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <% end %>
        <% if parent_folder.job_offers.empty? %>
        <% else %>
          <li role="separator" class="divider"></li>
          <% parent_folder.job_offers.each do |offer| %>
            <li><%= link_to offer.title, job_offer_job_applications_path(offer) %></li>
          <% end %>
        <% end %>
      </ul>
    </li>
    <% end %>
    <% if @orphan_offers == nil %>
    <% else %>
      <li role="separator" class="divider"></li>
      <% @orphan_offers.each do |offer| %>
        <li><%= link_to offer.title, job_offer_job_applications_path(offer) %></li>
      <% end %>
    <% end %>
  </ul>

</div>

<br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/job_offers/job_offer_star.js.erb
 // make the star yellow on click & vice versa
if ($( "<%= j '.offer-' + @job_offer.id.to_s %>" ).find(".star-icon").hasClass("fa-star-o")) {
  $( "<%= j '.offer-' + @job_offer.id.to_s %>" ).find(".star-icon").addClass("fa-star yellow").removeClass("fa-star-o gray-light");
}
else {
  $( "<%= j '.offer-' + @job_offer.id.to_s %>" ).find(".star-icon").addClass("fa-star-o gray-light").removeClass("fa-star yellow");
}

app/views/job_offers/show.html.erb
<!-- blue bar (bottom-border replica) -->
<div class="blue-bottom-border-fixed"></div>

<!-- CORE -->
<div class="black-background" id="job-offer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div class="cv-wrapper"> <!-- div englobbante  -->
          <h4 class="text-center job-offer-title"><%= @job_offer.title %></h4>
          <div class="job-offer-icons-div">
            <ul class="list-inline product-controls hidden-sm hidden-xs text-center">
              <li><i class="fa fa-globe"></i> <%= @job_offer.location %></li>
              <li><i class="fa fa-file-text"></i> <%= @job_offer.min_xp.to_i.to_s + "y - " + @job_offer.max_xp.to_i.to_s + "y" %></li>
              <li><i class="fa fa-money"></i> <%= @job_offer.salary.to_s + "K€" %></li>
            </ul>
          </div>
          <div class="job-offer-description">
            <p><%= simple_format @job_offer.description %></p>
          </div>
        </div> <!-- fin div englobbante  -->
      </div>
    </div>
  </div>

  <!-- APPLY NOW BAR -->
  <div class="apply-now-bar">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2 text-right">
          <% if recruiter_signed_in? %>
            <%= link_to "Edit offer", root_path, class: "btn btn-primary" %> <!-- replace with modal soon -->
          <% else %>
            <% if JobApplication.where(job_offer: @job_offer, candidate: current_candidate, submit: true).first %>
              <%= link_to "Already applied", "#", class: "btn btn-primary", id: "btn-recruiter" %>
            <% elsif JobApplication.where(job_offer: @job_offer, candidate: current_candidate).first %>
              <%= link_to "Continue application", new_job_offer_job_application_path(@job_offer), class: "btn btn-primary" %>
            <% else %>
              <%= link_to "Apply now", new_job_offer_job_application_path(@job_offer), class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div> <!-- apply now bar -->

</div> <!-- fin couleur de fond black -->